### ISSUE TITLE
Add TODO

### ISSUE THREAD

**Issue by ssvillarosa** [PUP-BSIT/project-hypefive_appdev#13]
Remove console log in your code. Instead, add a TODO in this format. https://docs.google.com/presentation/d/1Mdcq3WcHksBlbCvxi6wx5vajn4v8LGlJRnBIu3x4fvw/edit#slide=id.g2ce365fc06d_0_102
https://github.com/PUP-BSIT/project-hypefive_appdev/blob/032a5653302f4a5f8d2404b814ce3ca2c21649da/orgbee/src/app/login/login.component.ts#L103

Apply this to all your files and in your next codes.

**Comment by Ternal-AprilJoy** [comment]
This is noted Sir and will be implemented on our next codes. Thank you for your guidance.
