### ISSUE TITLE
Use FormBuilder

### ISSUE THREAD

**Issue by ssvillarosa** [PUP-BSIT/project-hypefive_appdev#5]
Use FormBuilder to build your forms. It will make your code cleaner and more readable.

Just added this to style guide. https://docs.google.com/presentation/d/1Mdcq3WcHksBlbCvxi6wx5vajn4v8LGlJRnBIu3x4fvw/edit#slide=id.g2e043376de2_0_0

https://github.com/PUP-BSIT/project-hypefive_appdev/blob/4253a64184bfc87318f5463e7ccda8bbe9931240/orgbee/src/app/login/login.component.ts#L16-L31

**Comment by Ternal-AprilJoy** [comment]
Noted po, Sir. We will change our approach and make sure to implement it accordingly.

**Comment by MentokAlmera** [comment]
We have already implemented the formBuilder approach, sir. Thank you for your guidance po.
